
CREATE TABLE file (
	container  TEXT        NOT NULL,
	path       TEXT        NOT NULL,
	part       INT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	dir        TEXT        NOT NULL,
	name       TEXT        NOT NULL,
	is_dir     BOOLEAN     NOT NULL,
	t_created  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	contents   BYTEA,
	PRIMARY KEY (container, path, part)
);

CREATE INDEX ON file (container, dir);